### ISSUE TITLE
Error: Cannot find module 'suncalc' (line:4)

### ISSUE THREAD

**Issue by Bodge-IT** [node-red/node-red-nodes#604]
#440 # Which node are you reporting an issue on?
node-red-node-suncalc

### What are the steps to reproduce?
none required, worked on 0.2.7
### What happens?
breaks after update to 1.0+
### What do you expect to happen?
works
### Please tell us about your environment:

- [ ] Node-RED version: 1.0.2 (nodered/node-red container)
- [ ] node.js version: ?
- [ ] npm version:?
- [ ] Platform/OS: Pi3b+ Rasbian
- [ ] Browser: FF & Chrome

**Comment by hardillb** [comment]
Please supply the node-red logs from start up, it will incur the reason why the node want loaded

**Comment by hardillb** [comment]
We also need the nodejs version, this will also be in the first few lines of the log

**Comment by Bodge-IT** [comment]
Welcome to Node-RED
===================

13 Nov 11:08:26 - [info] Node-RED version: v1.0.2
13 Nov 11:08:26 - [info] Node.js  version: v10.16.3
13 Nov 11:08:26 - [info] Linux 4.19.57-v7+ arm LE
13 Nov 11:08:28 - [info] Loading palette nodes
13 Nov 11:08:54 - [warn] ------------------------------------------------------
13 Nov 11:08:54 - [warn] [node-red-contrib-bigtimer/bigtimer] Error: Cannot find                                                    module 'suncalc' (line:12)
13 Nov 11:08:54 - [warn] [node-red-node-suncalc/suncalc] Error: Cannot find modu                                                   le 'suncalc' (line:4)
13 Nov 11:08:54 - [warn] ------------------------------------------------------
13 Nov 11:08:54 - [info] Settings file  : /data/settings.js
13 Nov 11:08:54 - [info] Context store  : 'default' [module=memory]
13 Nov 11:08:54 - [info] User directory : /data
13 Nov 11:08:54 - [warn] Projects disabled : set editorTheme.projects.enabled=tr                                                   ue to enable
13 Nov 11:08:54 - [info] Flows file     : /data/flows.json
13 Nov 11:08:54 - [info] Server now running at http://127.0.0.1:1880/
13 Nov 11:08:55 - [warn]


Nodejs

**Comment by Bodge-IT** [comment]
I didn't mention the Bigtimer issue as seemed to be caused by suncalc issue

**Comment by Bodge-IT** [comment]
I uninstalled and reinstalled, should I have restarted in between?

**Comment by knolleary** [comment]
You say you upgraded to 1.0.2 - and you are running in docker. This likely means the version of node.js has also been upgraded. That means any extra nodes you've installed that include binary components need rebuilding.

If you run: `docker exec -it mynodered /bin/bash` to get a shell inside the container (you'll need to replace `mynodered` with the name of your container) you can then go to `/data` and run `npm rebuild`. That should sort it out.

**Comment by Bodge-IT** [comment]
OK, @knolleary, I tried that, still no good.  The rebuild seemed to go through without anything needing building.  I would have assumed they would run that command within the container on load.
I did try npm update and got this:
```npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! request to https://registry.npmjs.org/node-red failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org registry.npmjs.org                            :443
npm ERR! A complete log of this run can be found in:
npm ERR!     /usr/src/node-red/.npm/_logs/2019-11-14T09_39_26_977Z-debug.log```

**Comment by dceejay** [comment]
I don't think there is any binary in suncalc.  The node-red-node-suncalc should drag it in as a prerequisite , without you installing it yourself.

**Comment by Bodge-IT** [comment]
@dceejay OK, not sure why it isn't but is there any way I can make that happen?

**Comment by dceejay** [comment]
uninstall and re-install it ?

**Comment by Bodge-IT** [comment]
@dceejay already tried that a couple of times

**Comment by hardillb** [comment]
But the error you mentioned when trying to reinstall in https://github.com/node-red/node-red-nodes/issues/604#issuecomment-553816336 shows a network resolution problem. Have you managed to actually have npm run cleanly when trying to install `node-red-node-suncalc`?

**Comment by Bodge-IT** [comment]
@hardillb Hi Ben, I'm seeing the error in palette manager.  When I uninstall the entry, it disappears then after install, it says it's installed but in the list shows the error.

**Comment by Bodge-IT** [comment]
@hardillb @dceejay @knolleary Solved my issue.  It was a combination of permissions and a file-lock preventing full suncalc install.  Used brute force to fix.
