### ISSUE TITLE
Error: Cannot find module 'node-pop3' after updating to 1.19.0

### ISSUE THREAD

**Issue by osvedman** [node-red/node-red-nodes#984]
### Which node are you reporting an issue on?
node-red-node-email

### What are the steps to reproduce?
1) Install node-red-node-email through the Node-RED palette
2) Insert a send email node and deploy the flow

### What happens?
MODULE_NOT_FOUND

Node-RED log:

```
28 Mar 09:12:25 - [info] Installing module: node-red-node-email, version: 1.19.0
28 Mar 09:12:36 - [info] Installed module: node-red-node-email
28 Mar 09:12:37 - [info] Added node types:
28 Mar 09:12:37 - [info]  - node-red-node-email:e-mail : Error: Cannot find module 'node-pop3'
Require stack:
- /home/pi/.node-red/node_modules/node-red-node-email/61-email.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/lib/node_modules/node-red/lib/red.js
- /usr/lib/node_modules/node-red/red.js
28 Mar 09:12:37 - [info]  - node-red-node-email:e-mail in : Error: Cannot find module 'node-pop3'
Require stack:
- /home/pi/.node-red/node_modules/node-red-node-email/61-email.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/lib/node_modules/node-red/lib/red.js
- /usr/lib/node_modules/node-red/red.js
28 Mar 09:12:37 - [info]  - node-red-node-email:e-mail mta : Error: Cannot find module 'node-pop3'
Require stack:
- /home/pi/.node-red/node_modules/node-red-node-email/61-email.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/lib/node_modules/node-red/lib/red.js
- /usr/lib/node_modules/node-red/red.js
28 Mar 09:12:45 - [info] Stopping modified nodes
28 Mar 09:12:45 - [info] Stopped modified nodes
28 Mar 09:12:45 - [info] Updated flows
28 Mar 09:12:45 - [info] Waiting for missing types to be registered:
28 Mar 09:12:45 - [info]  - e-mail (provided by npm module node-red-node-email)
28 Mar 09:12:45 - [info] To install any of these missing modules, run:
28 Mar 09:12:45 - [info]   npm install <module name>
28 Mar 09:12:45 - [info] in the directory:
28 Mar 09:12:45 - [info]   /home/pi/.node-red
```

### Please tell us about your environment:

- [x] Node-RED version: 3.0.2
- [x] node.js version: 16.19.1
- [x] npm version: 8.19.3
- [x] Platform/OS: Raspberry Pi 4

**Comment by osvedman** [comment]
I see that you have released 1.19.1 after this, but have not published it. I tried updating via the command line, but then I am hitting https://github.com/npm/cli/issues/4313

If 1.19.1 should work, can you please publish it?

(BTW, you also seem to have forgotten to publish node-red-dashboard v3.4.1)

**Comment by knolleary** [comment]
1.19.1 has been published to npm and updated on the flow library.

**Comment by osvedman** [comment]
You're right, my bad :(

1.19.1 works fine, closing this issue! Thank you for your quick response.
